import type { Preset, RigParams } from '../types/rig';

export const FACTORY_PRESETS: Preset[] = [
  // ─── Clean ───
  {
    name: 'Crystal Clean',
    category: 'clean',
    params: {
      gateThreshold: -60,
      gateAttack: 0.01,
      gateRelease: 0.1,
      drive: 0,
      tubeAmount: 0,
      bass: 2,
      mid: 0,
      treble: 3,
      presence: 2,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'optical',
      compThreshold: -18,
      compRatio: 2,
      compAttack: 10,
      compRelease: 200,
      compKnee: 6,
      compMakeup: 2,
      compMix: 1,
      compSaturation: 0,
      delayEnabled: true,
      delayType: 'digital',
      delayTime: 380,
      delayFeedback: 20,
      delayMix: 15,
      delayModDepth: 2,
      delayModRate: 0.5,
      delaySaturation: 0,
      delayDiffusion: 0.1,
      reverbEnabled: true,
      reverbType: 'room',
      reverbDecay: 1.2,
      reverbPreDelay: 15,
      reverbDamping: 0.3,
      reverbMix: 25,
      reverbRoomSize: 0.8,
      reverbModDepth: 0.5,
      reverbModRate: 0.3,
      reverbEarlyLevel: 0.7,
      reverbShimmer: 0,
      masterVolume: 1.0,
    },
  },

  // ─── Crunch ───
  {
    name: 'Blues Breaker',
    category: 'crunch',
    params: {
      gateThreshold: -55,
      gateAttack: 0.01,
      gateRelease: 0.15,
      drive: 0.25,
      tubeAmount: 0.4,
      bass: 1,
      mid: 2,
      treble: 1,
      presence: 1,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'tube',
      compThreshold: -22,
      compRatio: 3,
      compAttack: 5,
      compRelease: 150,
      compKnee: 4,
      compMakeup: 3,
      compMix: 1,
      compSaturation: 0.1,
      delayEnabled: true,
      delayType: 'analog',
      delayTime: 420,
      delayFeedback: 30,
      delayMix: 20,
      delayModDepth: 3,
      delayModRate: 0.4,
      delaySaturation: 0.15,
      delayDiffusion: 0.2,
      reverbEnabled: true,
      reverbType: 'spring',
      reverbDecay: 1.8,
      reverbPreDelay: 20,
      reverbDamping: 0.5,
      reverbMix: 20,
      reverbRoomSize: 1.0,
      reverbModDepth: 0.8,
      reverbModRate: 0.4,
      reverbEarlyLevel: 0.6,
      reverbShimmer: 0,
      masterVolume: 1.0,
    },
  },

  {
    name: 'Classic Rock',
    category: 'crunch',
    params: {
      gateThreshold: -50,
      gateAttack: 0.005,
      gateRelease: 0.1,
      drive: 0.45,
      tubeAmount: 0.5,
      bass: 3,
      mid: 1,
      treble: 2,
      presence: 2,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'fet',
      compThreshold: -20,
      compRatio: 4,
      compAttack: 2,
      compRelease: 100,
      compKnee: 3,
      compMakeup: 4,
      compMix: 1,
      compSaturation: 0.2,
      delayEnabled: true,
      delayType: 'tape',
      delayTime: 350,
      delayFeedback: 25,
      delayMix: 18,
      delayModDepth: 4,
      delayModRate: 0.6,
      delaySaturation: 0.25,
      delayDiffusion: 0.3,
      reverbEnabled: true,
      reverbType: 'plate',
      reverbDecay: 2.0,
      reverbPreDelay: 25,
      reverbDamping: 0.4,
      reverbMix: 22,
      reverbRoomSize: 1.1,
      reverbModDepth: 1.0,
      reverbModRate: 0.5,
      reverbEarlyLevel: 0.65,
      reverbShimmer: 0,
      masterVolume: 1.0,
    },
  },

  // ─── High-Gain ───
  {
    name: 'Metal Machine',
    category: 'high-gain',
    params: {
      gateThreshold: -45,
      gateAttack: 0.001,
      gateRelease: 0.05,
      drive: 0.85,
      tubeAmount: 0.8,
      bass: 5,
      mid: -3,
      treble: 4,
      presence: 3,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'vca',
      compThreshold: -16,
      compRatio: 6,
      compAttack: 1,
      compRelease: 80,
      compKnee: 2,
      compMakeup: 6,
      compMix: 1,
      compSaturation: 0.3,
      delayEnabled: false,
      delayType: 'digital',
      delayTime: 300,
      delayFeedback: 35,
      delayMix: 25,
      delayModDepth: 0,
      delayModRate: 0,
      delaySaturation: 0,
      delayDiffusion: 0.05,
      reverbEnabled: true,
      reverbType: 'hall',
      reverbDecay: 1.5,
      reverbPreDelay: 10,
      reverbDamping: 0.6,
      reverbMix: 12,
      reverbRoomSize: 1.2,
      reverbModDepth: 0,
      reverbModRate: 0,
      reverbEarlyLevel: 0.5,
      reverbShimmer: 0,
      masterVolume: 0.9,
    },
  },

  {
    name: 'Djent Core',
    category: 'high-gain',
    params: {
      gateThreshold: -40,
      gateAttack: 0.001,
      gateRelease: 0.03,
      drive: 0.95,
      tubeAmount: 0.9,
      bass: 6,
      mid: -5,
      treble: 5,
      presence: 4,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'brickwall',
      compThreshold: -12,
      compRatio: 10,
      compAttack: 0.5,
      compRelease: 50,
      compKnee: 1,
      compMakeup: 8,
      compMix: 1,
      compSaturation: 0.4,
      delayEnabled: false,
      delayType: 'digital',
      delayTime: 300,
      delayFeedback: 35,
      delayMix: 25,
      delayModDepth: 0,
      delayModRate: 0,
      delaySaturation: 0,
      delayDiffusion: 0.05,
      reverbEnabled: false,
      reverbType: 'room',
      reverbDecay: 0.8,
      reverbPreDelay: 5,
      reverbDamping: 0.7,
      reverbMix: 8,
      reverbRoomSize: 0.6,
      reverbModDepth: 0,
      reverbModRate: 0,
      reverbEarlyLevel: 0.4,
      reverbShimmer: 0,
      masterVolume: 0.85,
    },
  },

  // ─── Ambient ───
  {
    name: 'Shimmer Wash',
    category: 'ambient',
    params: {
      gateThreshold: -60,
      gateAttack: 0.02,
      gateRelease: 0.3,
      drive: 0.1,
      tubeAmount: 0.2,
      bass: 0,
      mid: 0,
      treble: 2,
      presence: 3,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'optical',
      compThreshold: -24,
      compRatio: 2,
      compAttack: 15,
      compRelease: 300,
      compKnee: 8,
      compMakeup: 1,
      compMix: 0.5,
      compSaturation: 0,
      delayEnabled: true,
      delayType: 'shimmer',
      delayTime: 500,
      delayFeedback: 45,
      delayMix: 40,
      delayModDepth: 8,
      delayModRate: 1.2,
      delaySaturation: 0.1,
      delayDiffusion: 0.6,
      reverbEnabled: true,
      reverbType: 'shimmer',
      reverbDecay: 8.0,
      reverbPreDelay: 60,
      reverbDamping: 0.2,
      reverbMix: 55,
      reverbRoomSize: 1.5,
      reverbModDepth: 3,
      reverbModRate: 1.0,
      reverbEarlyLevel: 0.3,
      reverbShimmer: 0.7,
      masterVolume: 1.0,
    },
  },

  {
    name: 'Post-Rock Space',
    category: 'ambient',
    params: {
      gateThreshold: -55,
      gateAttack: 0.01,
      gateRelease: 0.2,
      drive: 0.15,
      tubeAmount: 0.3,
      bass: 2,
      mid: -1,
      treble: 3,
      presence: 4,
      cabEnabled: true,
      cabIR: '/ir/IR-meza.wav',
      compEnabled: true,
      compType: 'glue',
      compThreshold: -20,
      compRatio: 2.5,
      compAttack: 8,
      compRelease: 250,
      compKnee: 6,
      compMakeup: 2,
      compMix: 0.7,
      compSaturation: 0.05,
      delayEnabled: true,
      delayType: 'modulated',
      delayTime: 600,
      delayFeedback: 40,
      delayMix: 35,
      delayModDepth: 10,
      delayModRate: 2.0,
      delaySaturation: 0.2,
      delayDiffusion: 0.5,
      reverbEnabled: true,
      reverbType: 'cathedral',
      reverbDecay: 12.0,
      reverbPreDelay: 80,
      reverbDamping: 0.15,
      reverbMix: 45,
      reverbRoomSize: 1.8,
      reverbModDepth: 4,
      reverbModRate: 1.5,
      reverbEarlyLevel: 0.25,
      reverbShimmer: 0.4,
      masterVolume: 1.0,
    },
  },
];

export function getPresetsByCategory(category: Preset['category']): Preset[] {
  return FACTORY_PRESETS.filter(p => p.category === category);
}

export function getAllCategories(): Preset['category'][] {
  return ['clean', 'crunch', 'high-gain', 'ambient', 'custom'];
}